# Site settings
title: Camilo Luna
email: camilo@camiloluna.com
description: Ideas poderosas, opiniones debatibles.
author: Camilo Luna
timezone: America/Bogota
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
site.lang: es
permalink: /:title/